baseurl = "https://sasi.netlify.com/"
title = "SASI"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id


[Params]
    subtitle = "Student Association of the School of Information" # Subtitle of your site
    description = "SASI website" # Description of your site
    opengraph = true
    readmore = false # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true
    post_navigation = true
    postSections = ["post"]


[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
        tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
